#!/usr/bin/env python3
"""ia-map-aggregator.py

聚合所有 slice 的 Product Surface 字段, 输出 markdown 表 (IA Map)。

用途: 在 .opc/implementation-plan/index.md 自动维护一份 IA 总图,
让代理实现到一半就能一眼看到 IA 全貌、发现高曝光入口超 5 的硬约束。

Usage:
  python3 ia-map-aggregator.py --slices <slices-dir>
  python3 ia-map-aggregator.py --slices <slices-dir> --update-index <index.md>

输出模式:
  - 不带 --update-index: 打印到 stdout
  - 带 --update-index: 替换 index.md 中两个 marker 之间的内容; 没有 marker 时
                       append 到文件末尾

退出码:
  0 = 成功
  1 = 参数错误或文件不存在
  2 = 高曝光入口超过 5 (硬卡) - CI 可用此退出码阻断
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path
from typing import NamedTuple


IA_MAP_BEGIN = "<!-- ia-map:begin (auto-generated by ia-map-aggregator.py) -->"
IA_MAP_END = "<!-- ia-map:end -->"
HIGH_EXPOSURE_HARD_CAP = 5


class ProductSurfaceRow(NamedTuple):
    slice_id: str
    capability: str
    target_level: str
    actual_level: str
    location: str
    consistency: str


def parse_slice_id(path: Path) -> str:
    return path.stem


def extract_product_surface(content: str) -> str | None:
    """提取 ## Product Surface section 内容 (不含 header)。"""
    lines = content.splitlines()
    in_section = False
    section_lines: list[str] = []
    for line in lines:
        stripped = line.strip()
        if stripped.startswith("## "):
            if in_section:
                break
            if "Product Surface" in stripped:
                in_section = True
                continue
        if in_section:
            section_lines.append(line)
    if not section_lines:
        return None
    return "\n".join(section_lines).strip()


def parse_field(section_text: str, field_label: str) -> str:
    """从 Product Surface section 里提取字段值。字段格式: "- <label>: <value>" """
    pattern = re.compile(
        rf"^\s*-\s*{re.escape(field_label)}\s*[:：]\s*(.+?)\s*$",
        re.MULTILINE,
    )
    m = pattern.search(section_text)
    return m.group(1).strip() if m else ""


def detect_na(section_text: str) -> bool:
    """检查是否标记为 N/A (后端 / 基建 / 数据迁移 slice)。"""
    for line in section_text.splitlines():
        s = line.strip().lstrip("-").lstrip("*").strip()
        if not s:
            continue
        sl = s.lower()
        if sl in ("n/a", "na"):
            return True
        if sl.startswith("n/a (") or sl.startswith("na ("):
            return True
        if sl.startswith("n/a:") or sl.startswith("na:"):
            return True
        # 第一个非空行不是 N/A 声明 → 走正常字段解析
        break
    return False


def parse_consistency(section_text: str) -> str:
    """解析一致性字段, 归一化为 ✓ / ⚠️ / ❌ / 原文。"""
    raw = parse_field(section_text, "一致性")
    if not raw:
        return ""
    if "✓" in raw or raw.startswith("一致"):
        return "✓"
    if "⚠" in raw or "偏离" in raw:
        return "⚠️"
    if "❌" in raw or "矛盾" in raw or "新能力" in raw:
        return "❌"
    return raw[:20]


def is_high_exposure(actual_level: str) -> bool:
    """判断该 slice 实际是否落在高曝光位置 (一级导航 / 首页主区)。"""
    text = actual_level.lower()
    return any(
        kw in text
        for kw in ("高曝光", "一级", "首页主区", "首页", "top-level", "primary nav")
    )


def aggregate(slices_dir: Path) -> list[ProductSurfaceRow]:
    rows: list[ProductSurfaceRow] = []
    for slice_file in sorted(slices_dir.glob("*.md")):
        content = slice_file.read_text(encoding="utf-8", errors="ignore")
        slice_id = parse_slice_id(slice_file)
        section = extract_product_surface(content)
        if section is None:
            continue
        if detect_na(section):
            continue
        rows.append(
            ProductSurfaceRow(
                slice_id=slice_id,
                capability=parse_field(section, "对应升降级表能力") or "—",
                target_level=parse_field(section, "升降级表标的层级") or "—",
                actual_level=parse_field(section, "实际实现层级") or "—",
                location=parse_field(section, "入口位置") or "—",
                consistency=parse_consistency(section),
            )
        )
    return rows


def render_table(rows: list[ProductSurfaceRow]) -> str:
    if not rows:
        return "_(暂无 UI slice 含 Product Surface 字段)_"
    header = (
        "| Slice | 能力 | 标的层级 | 实际层级 | 位置 | 一致 |\n"
        "|---|---|---|---|---|---|\n"
    )
    body = "\n".join(
        f"| {r.slice_id} | {r.capability} | {r.target_level} | {r.actual_level} | {r.location} | {r.consistency} |"
        for r in rows
    )
    return header + body


def render_summary(rows: list[ProductSurfaceRow]) -> tuple[str, int]:
    """返回 (摘要文本, 高曝光数)。"""
    if not rows:
        return "", 0
    n_total = len(rows)
    n_ok = sum(1 for r in rows if r.consistency == "✓")
    n_warn = sum(1 for r in rows if r.consistency == "⚠️")
    n_fail = sum(1 for r in rows if r.consistency == "❌")
    high_count = sum(1 for r in rows if is_high_exposure(r.actual_level))

    warning = ""
    if high_count > HIGH_EXPOSURE_HARD_CAP:
        warning = (
            f"\n\n⚠️ 实际高曝光入口数 = {high_count}, 超过硬卡 ≤{HIGH_EXPOSURE_HARD_CAP}。"
            " 必须降级若干能力到二级 / 设置 / 仅上下文。"
        )

    summary = (
        f"\n\n**统计**: 总 {n_total} 项 — 一致 {n_ok} / 偏离 {n_warn} / 矛盾 {n_fail}; "
        f"高曝光入口 {high_count}" + warning
    )
    return summary, high_count


def update_index(index_path: Path, body: str) -> bool:
    """更新 index.md 的 IA Map 区域。Marker 不存在时 append。"""
    content = index_path.read_text(encoding="utf-8", errors="ignore")
    block = f"{IA_MAP_BEGIN}\n## IA Map\n\n{body}\n{IA_MAP_END}"

    pattern = re.compile(
        re.escape(IA_MAP_BEGIN) + r".*?" + re.escape(IA_MAP_END),
        re.DOTALL,
    )
    if pattern.search(content):
        new_content = pattern.sub(block, content)
    else:
        new_content = content.rstrip() + "\n\n" + block + "\n"

    if new_content == content:
        return False
    index_path.write_text(new_content, encoding="utf-8")
    return True


def main() -> int:
    parser = argparse.ArgumentParser(
        description="聚合 slices/*.md 的 Product Surface 字段成 IA Map 表"
    )
    parser.add_argument(
        "--slices",
        type=Path,
        required=True,
        help="slices 目录, 例: .opc/implementation-plan/slices",
    )
    parser.add_argument(
        "--update-index",
        type=Path,
        help="可选, 更新此 index.md 的 IA Map section",
    )
    args = parser.parse_args()

    if not args.slices.is_dir():
        print(f"ERROR: --slices 目录不存在: {args.slices}", file=sys.stderr)
        return 1

    rows = aggregate(args.slices)
    table = render_table(rows)
    summary_text, high_count = render_summary(rows)
    body = table + summary_text

    if args.update_index:
        if not args.update_index.is_file():
            print(
                f"ERROR: --update-index 文件不存在: {args.update_index}",
                file=sys.stderr,
            )
            return 1
        changed = update_index(args.update_index, body)
        print(f"{'updated' if changed else 'unchanged'}: {args.update_index}")
    else:
        print("## IA Map\n")
        print(body)

    if high_count > HIGH_EXPOSURE_HARD_CAP:
        return 2
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
